# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-01 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180531_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='status',
            field=models.BooleanField(default=True, verbose_name=orders.models.Status),
        ),
    ]
