# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-02 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_productinorder_price_per_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='status',
            new_name='is_active',
        ),
    ]
