# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-05 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='product',
            new_name='products',
        ),
    ]
