# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-30 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180531_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/products_images/'),
        ),
    ]
