# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-04 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180604_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='сategory',
        ),
    ]
